export type PageKey =
  | "dashboard"
  | "lancamentos"
  | "contas"
  | "contas_futuras"
  | "dinheiro_separado"
  | "orcamento"
  | "cartoes"
  | "patrimonio"
  | "investimentos"
  | "desempenho"
  | "dividendos"
  | "exterior"
  | "relatorios"
  | "configuracoes"
  | "integracoes";
